<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Voidstep.Core</AssemblyName>
    <RootNamespace>Voidstep.Core</RootNamespace>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>